apiVersion: v1
kind: Service
metadata:
  name: contoso
  namespace: default
spec:
  selector:
    app: contoso
  type: LoadBalancer
  ports:
  - name: contoso
    port: 80
    targetPort: 80 
    protocol: TCP